CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    username      VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    bio           TEXT,
    profile_image VARCHAR(255),
    role          VARCHAR(255)                            NOT NULL,
    is_active     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);