CREATE TABLE wallet
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    user_id      BIGINT                                 NOT NULL,
    balance_gold BIGINT                                 NOT NULL DEFAULT 0,
    version      BIGINT,
    CONSTRAINT pk_wallet PRIMARY KEY (id),
    CONSTRAINT uc_wallet_user UNIQUE (user_id),
    CONSTRAINT fk_wallet_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_wallet_user_id ON wallet (user_id);

CREATE TABLE wallet_txn
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT                                 NOT NULL,
    amount     BIGINT                                 NOT NULL,
    type       VARCHAR(50)                            NOT NULL,
    ref_type   VARCHAR(50),
    ref_id     BIGINT,
    note       TEXT,
    CONSTRAINT pk_wallet_txn PRIMARY KEY (id),
    CONSTRAINT fk_wallet_txn_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_wallet_txn_user_id ON wallet_txn (user_id);
CREATE INDEX idx_wallet_txn_ref ON wallet_txn (ref_type, ref_id);
CREATE INDEX idx_wallet_txn_created_at ON wallet_txn (created_at);
