
CREATE TABLE tables
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,

    owner_user_id  BIGINT                                 NOT NULL,

    status         VARCHAR(50)                            NOT NULL,
    mode           VARCHAR(50)                            NOT NULL,
    badge_tier     VARCHAR(50),

    stake_gold     INTEGER                                NOT NULL,
    target_score   INTEGER                                NOT NULL,

    seat0_user_id  BIGINT,
    seat1_user_id  BIGINT,

    -- optional: join races
    version        BIGINT,

    CONSTRAINT pk_tables PRIMARY KEY (id),
    CONSTRAINT fk_tables_owner FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT fk_tables_seat0 FOREIGN KEY (seat0_user_id) REFERENCES users (id),
    CONSTRAINT fk_tables_seat1 FOREIGN KEY (seat1_user_id) REFERENCES users (id),

    CONSTRAINT chk_tables_stake_positive CHECK (stake_gold > 0),
    CONSTRAINT chk_tables_target_positive CHECK (target_score > 0)
);

CREATE INDEX idx_tables_status ON tables (status);
CREATE INDEX idx_tables_owner ON tables (owner_user_id);
CREATE INDEX idx_tables_created_at ON tables (created_at);
CREATE INDEX idx_tables_seats ON tables (seat0_user_id, seat1_user_id);

CREATE TABLE wager_lock
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    table_id   BIGINT                                 NOT NULL,
    user_id    BIGINT                                 NOT NULL,

    stake_gold INTEGER                                NOT NULL,
    status     VARCHAR(50)                            NOT NULL DEFAULT 'LOCKED',

    CONSTRAINT pk_wager_lock PRIMARY KEY (id),
    CONSTRAINT fk_wager_lock_table FOREIGN KEY (table_id) REFERENCES tables (id),
    CONSTRAINT fk_wager_lock_user FOREIGN KEY (user_id) REFERENCES users (id),

    CONSTRAINT uc_wager_lock_table_user UNIQUE (table_id, user_id),
    CONSTRAINT chk_wager_lock_stake_positive CHECK (stake_gold > 0)
);

CREATE INDEX idx_wager_lock_table ON wager_lock (table_id);
CREATE INDEX idx_wager_lock_user ON wager_lock (user_id);
CREATE INDEX idx_wager_lock_status ON wager_lock (status);
