CREATE TABLE games
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,

    table_id     BIGINT                                 NOT NULL,
    status       VARCHAR(50)                            NOT NULL,
    target_score INTEGER                                NOT NULL,

    winner_seat  INTEGER,
    finished_at  TIMESTAMP WITHOUT TIME ZONE,

    state_json   TEXT,

    CONSTRAINT pk_games PRIMARY KEY (id),
    CONSTRAINT uc_games_table UNIQUE (table_id),
    CONSTRAINT fk_games_table FOREIGN KEY (table_id) REFERENCES tables (id),
    CONSTRAINT chk_games_target_positive CHECK (target_score > 0)
);

CREATE INDEX idx_games_status ON games (status);
CREATE INDEX idx_games_created_at ON games (created_at);